/*
 * ParticleSimView.java
 */

package particlesim;

import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.clapper.util.classutil.*;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/**
 * The application's main frame.
 */
public class ParticleSimView extends FrameView {
    // Used for running the calculations and drawing routines in a background thread.
    DrawParticles draw;

    public ParticleSimView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });

        // Call the routine to populate the particle combobox.
        PopulateParticleCombo();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = ParticleSimApp.getApplication().getMainFrame();
            aboutBox = new ParticleSimAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ParticleSimApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbPType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtNumP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlChars = new javax.swing.JList();
        jbRun = new javax.swing.JButton();
        bpGraphics = new particlesim.BufferedPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jmRun = new javax.swing.JCheckBoxMenuItem();
        jmLoad = new javax.swing.JMenuItem();
        jmSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(particlesim.ParticleSimApp.class).getContext().getResourceMap(ParticleSimView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jcbPType.setFont(resourceMap.getFont("jcbPType.font")); // NOI18N
        jcbPType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(particlesim.ParticleSimApp.class).getContext().getActionMap(ParticleSimView.class, this);
        jcbPType.setAction(actionMap.get("ParticleTypeSelected")); // NOI18N
        jcbPType.setEditor(null);
        jcbPType.setName("jcbPType"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jtNumP.setText(resourceMap.getString("jtNumP.text")); // NOI18N
        jtNumP.setName("jtNumP"); // NOI18N
        jtNumP.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtNumPInputMethodTextChanged(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jlChars.setName("jlChars"); // NOI18N
        jlChars.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlCharsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlChars);

        jbRun.setText(resourceMap.getString("jbRun.text")); // NOI18N
        jbRun.setName("jbRun"); // NOI18N
        jbRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRunMouseClicked(evt);
            }
        });

        bpGraphics.setBackground(resourceMap.getColor("bpGraphics.background")); // NOI18N
        bpGraphics.setName("bpGraphics"); // NOI18N

        org.jdesktop.layout.GroupLayout bpGraphicsLayout = new org.jdesktop.layout.GroupLayout(bpGraphics);
        bpGraphics.setLayout(bpGraphicsLayout);
        bpGraphicsLayout.setHorizontalGroup(
            bpGraphicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 437, Short.MAX_VALUE)
        );
        bpGraphicsLayout.setVerticalGroup(
            bpGraphicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 368, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(jbRun))
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel2))
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jtNumP, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jcbPType, 0, 129, Short.MAX_VALUE))
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3))
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bpGraphics, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(7, 7, 7)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jtNumP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcbPType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(60, 60, 60)
                .add(jbRun)
                .addContainerGap())
            .add(bpGraphics, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        jmRun.setText(resourceMap.getString("jmRun.text")); // NOI18N
        jmRun.setName("jmRun"); // NOI18N
        jmRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRunMouseClicked(evt);
            }
        });
        fileMenu.add(jmRun);

        jmLoad.setText(resourceMap.getString("jmLoad.text")); // NOI18N
        jmLoad.setName("jmLoad"); // NOI18N
        fileMenu.add(jmLoad);

        jmSave.setText(resourceMap.getString("jmSave.text")); // NOI18N
        jmSave.setName("jmSave"); // NOI18N
        fileMenu.add(jmSave);

        jSeparator1.setName("jSeparator1"); // NOI18N
        fileMenu.add(jSeparator1);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuItem_mouseClicked(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        org.jdesktop.layout.GroupLayout statusPanelLayout = new org.jdesktop.layout.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .add(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(statusMessageLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 458, Short.MAX_VALUE)
                .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelLayout.createSequentialGroup()
                .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(statusMessageLabel)
                    .add(statusAnimationLabel)
                    .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItem_mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuItem_mouseClicked
        ParticleSimApp.getApplication().exit();
    }//GEN-LAST:event_exitMenuItem_mouseClicked

    private void jlCharsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlCharsValueChanged
        // Update the value in the jtCharMod textbox to reflect the selected item's value.
    }//GEN-LAST:event_jlCharsValueChanged

    private void jbRunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRunMouseClicked
        // Run the particle simulation.
        this.ToggleRunStop();
    }//GEN-LAST:event_jbRunMouseClicked

    private void jtNumPInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtNumPInputMethodTextChanged
        // Only numeric values are allowed in the jtNumP textbox.
    }//GEN-LAST:event_jtNumPInputMethodTextChanged

    private void jmRunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRunMouseClicked
        // Run the particle simulation.
        this.ToggleRunStop();
    }//GEN-LAST:event_jmRunMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private particlesim.BufferedPanel bpGraphics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbRun;
    private javax.swing.JComboBox jcbPType;
    private javax.swing.JList jlChars;
    private javax.swing.JMenuItem jmLoad;
    private javax.swing.JCheckBoxMenuItem jmRun;
    private javax.swing.JMenuItem jmSave;
    private javax.swing.JTextField jtNumP;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;

    private void PopulateParticleCombo()
    {
        // Populate the combo box with all of the classes that exist, which implement the IParticle interface.
        ClassFinder finder = new ClassFinder();
        finder.addClassPath();
        
        ClassFilter filter = new SubclassClassFilter(particlesim.IParticle.class);

        Collection<ClassInfo> foundClasses = new ArrayList<ClassInfo>();
        finder.findClasses (foundClasses, filter);

        for (ClassInfo classInfo : foundClasses)
            this.jcbPType.addItem(classInfo.getClassName()); //.substring(classInfo.getClassName().lastIndexOf(".")+1));

    }

    @Action
    public void ParticleTypeSelected() {
        String sSelItem = this.jcbPType.getSelectedItem().toString();

        // Load and initialize the selected particle type.
        Class p = null;
        try {
            p = Class.forName(sSelItem);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ParticleSimView.class.getName()).log(Level.SEVERE, null, ex);
        }

        //TODO Make the following better. The Class.forName function above may be useful....
        // Determine what particle type was selected and load the corresponding class.
        if(p.toString().equals(ChargedParticle.class.toString()))
        {
            // Load the ChargedParticle class and fill the characteristics
            // into the characteristics listbox.
            ChargedParticle cp = new ChargedParticle();
            DefaultListModel list = new DefaultListModel();
            this.jlChars.setModel(list);

            for(int i=0;i<cp.getCharacteristic().length;i++)
                list.addElement(cp.getCharacteristic()[i].getCharacteristicType().getName());
        }
    }

    private void DoRun()
    {
        // Clear the graphics panel.
        this.bpGraphics.getGraphics().clearRect(0, 0, this.bpGraphics.getWidth(), this.bpGraphics.getHeight());

        // An array of particles to pass between this and that.
        particlesim.IParticle[] parts;

        // Instantiate the Calculate class for the selected particle type
        // and have it create the number particles indicated by the user.
        String sSelItem = this.jcbPType.getSelectedItem().toString();

        // Load and initialize the selected particle type.
        Class p = null;
        try {
            p = Class.forName(sSelItem);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ParticleSimView.class.getName()).log(Level.SEVERE, null, ex);
        }

        //TODO Make the following better. The Class.forName function above may be useful....
        // Determine what particle type was selected and load the corresponding class.
        if(p.toString().equals(ChargedParticle.class.toString()))
        {
            CalculateCharged cc = new CalculateCharged();
            
            // Initialize the particle array.
            parts = cc.InitializeParticles(Integer.parseInt(this.jtNumP.getText()), this.bpGraphics.getWidth(), this.bpGraphics.getHeight(), 0);

            // In a new thread, launch the routine that handles the drawing and calculating of forces and positions.
            draw = new DrawParticles(this.bpGraphics, parts);
            draw.execute();
        }
    }

    private void ToggleRunStop()
    {
        if(this.jbRun.getText().equals("Run"))
        {
            this.jbRun.setText("Stop");
            this.DoRun();
        }
        else
        {
            this.jbRun.setText("Run");
            draw.cancel(true);
        }
    }
}
